/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Hp' at '17/10/20 9:37 AM' with Gradle 3.0
 *
 * @author Hp, @date 17/10/20 9:37 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
